### PR TITLE
Speed up carton/program query

### PR DESCRIPTION
**Pull request by imedan**
I have added a small amount of code to try to speed up the carton/program query. Now I simply disable sequential scanning for this specific query, which decreases query times in most cases. It should be noted for the largest carton (GG) this makes the query slower.

### CODE REVIEW

**Comment by havok2063** [comment]
Does the atomic transaction need to wrap at the route level, or can it be moved into the `carton_program_search` function?  Another question I have is how will this affect queries that need to be joined with this?  For example, if you joined a `cone_search` with the `carton_program_search` query, does the logic and/or performance change?   

Should we just flat disable sequential scans for all queries?

**Comment by imedan** [comment]
> Does the atomic transaction need to wrap at the route level, or can it be moved into the `carton_program_search` function?

I believe it needs to be wrapped wherever the query is actually executed? This doesn't actually happen within the function, it only constructs the query, and then the query is executed at the route level.

> Another question I have is how will this affect queries that need to be joined with this? For example, if you joined a `cone_search` with the `carton_program_search' query, does the logic and/or performance change?

I imagine is they are joined via another route, this means no you will not get the improved performance. This does seem less than ideal. It would be good if @albireox could comment at this point as I am not super familiar with how to better utilizer the atomic transaction.

> Should we just flat disable sequential scans for all queries?

Similarly, I think @albireox should comment here. I imagine the answer is no? This doesn't seem wise to do this as default to me at least.

**Comment by havok2063** [comment]
@imedan Is this ready to be reviewed?

**Comment by albireox** [comment]
Sorry, missed the original mentions.

Regarding the performance when a cone search (or anything with a `q3c` index) is combined with other `WHERE` conditions. In those cases, almost always, the `q3c` index is lost and the performance is much worst. I think this has to do with the query planner not being able to understand how to use the `q3c` index in combination with other indices. In these cases I have found that the best way is to always do the cone search first without additional constraints, and pipe it to a temporary table. Then from that temporary table one can join and apply other conditions. In that temporary table one can create indices if that helps speeds things up. In general, one can check whether the `q3c` index is being used by explaining the query. One should see a `BitmapOr` with many sub index conditions like

```
Index Cond: ((q3c_ang2ipix(ra, "dec") >= '1'::bigint) AND (q3c_ang2ipix(ra, "dec") < '-1'::bigint))
```

If you don't see those, most likely the index is not being used or not being used properly. In some cases, the index may not be used if the `work_mem` or local memory is too small, but I think the defaults in the pipeline machine should generally prevent that.

I would generally not disable sequential scans and only do it within transactions when it makes sense. Sequential scans are a bit different because sometimes they are the only way of performing a query, so the query planner will use them as a last resource even if `enable_seqscan=false`, but it will try very hard not to, and in some cases you do want the sequential scan. So, you can try disabling it globally and see what happens, but I'd probably disable it locally.

**Comment by imedan** [comment]
Ok, it seems like to me we should leave this as is and add in additional instances of `enable_seqscan=false` where it may be needed. I will make this as ready to review.

**Comment by havok2063** [comment]
@imedan can you resolve the conflicts with main?

**Comment by imedan** [comment]
@havok2063, the conflicts should all be resolved now.

**Pull request merged**
